name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pillow

      - name: Build executable
        run: pyinstaller --noconfirm --onedir --windowed --icon "./workers.ico" --name "HumanResourceDepartment" --contents-directory "." --add-data "./HumanResourceDepartment.db:." --add-data "./photos/background.png:photos/" --add-data "./photos/workers.png:photos/" "./main.py"

      - name: Create zip archive
        run: |
          cd dist
          zip -r HumanResourceDepartment.zip HumanResourceDepartment

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: HumanResourceDepartment
          path: dist/HumanResourceDepartment.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: HumanResourceDepartment
          path: .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            First release of HumanResourceDepartment application

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/HumanResourceDepartment.zip
          asset_name: HumanResourceDepartment.zip
          asset_content_type: application/zip
